title: "ControlGenie"
description: ""
url: "https://controlgenie.io"

github-url: "https://github.com/ControlGenie/home"
github-branch: "gh-pages"

author:
  name: Romero Galiza
  url: https://controlgenie.io
  email: controlgenie@proton.me

markdown: kramdown

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-timeago

permalink: /:year-:month-:day/:title:output_ext
paginate: 8
